task :default =>  [:execute]
task :test => [:spec
]
# rake execute or rake
desc "Executes the flattenize program"
task :execute do
  require File.expand_path('examples/example.rb', '.')
  if RUBY_VERSION.to_f < 1.9
    puts "--> Please use ruby version 1.9.x and onwards"
  else
    Example.example_1
    Example.example_2
    Example.example_3
  end
end

# rake spec or rake test
desc "Execute rspec test cases"
task :spec do
	sh 'rspec spec/*_spec.rb --format nested --color'
end
