task :default =>  [:execute]
task :test => [:spec
]
# rake execute or rake
desc "Executes the flattenize program"
task :execute do
  if RUBY_VERSION.to_f < 1.9
    puts "--> Please use ruby version 1.9.x and onwards"
  else
    sh "ruby lib/flattenize.rb"
  end
end

# rake spec or rake test
desc "Execute rspec test cases"
task :spec do
	sh 'rspec spec/*_spec.rb --format nested --color'
end
